<script>
    require(['jquery', 'js-cookie/cookie-wrapper'], function($){
        $(document).on('click', '.amcheckout-wrapper input[type="radio"]', function(){
            if($(this).val() == "okinus_payment"){
                $(".action.primary.checkout.amasty span").text("Pay with <?= $block->getBranding() ?>");
            }else{
                $(".action.primary.checkout.amasty span").text("Place Order");
            }
        });

        $(document).ready(function() {
            setTimeout(function() {
                if($('.amcheckout-wrapper input[type="radio"]:checked').val() == "okinus_payment"){
                    $(".action.primary.checkout.amasty span").text("Pay with <?= $block->getBranding() ?>");
                }else{
                    $(".action.primary.checkout.amasty span").text("Place Order");
                }
            }, 5000);
        });

        function initiateApply(){
            okinus.apply(function(payload){
                // console.log("okinus_payment",payload)
                if (payload.step == 'CHECKOUT_APP_COMPLETE' && payload.status == 'approved') {
                    console.log('payload', payload);
                    let approvalData = payload.data;
                    let approvalAmounts = approvalData.offerAmounts;
                    let okinus_application_id = approvalData.applicationId;
					var returnedApprovalAmounts = [];
                    var i = 0;
					for (var key in approvalAmounts) {
						if (approvalAmounts[key] !== " ")
                        {
							returnedApprovalAmounts.push(parseFloat(approvalAmounts[key].replace(/,/g, '')));
                            if(i == undefined)
                            {
                                return false;
                            }
                            i++;
						}
					}
					var okinusAmountApproved = Math.max.apply(Math, returnedApprovalAmounts).toFixed(2).replace(/,/g, '');
                    $.cookie('okinus_approval_amount', okinusAmountApproved, {expires: 86400});
                    $.cookie('okinus_application_id', okinus_application_id, {expires: 86400});

                    $('.okinus-widget').show();

                    $.ajax({
                        url: '/okinus/cart/checkprice',
                        method: 'post'
                    }).done(function(response){
                        $.cookie('okinus_approval_amount_format', response.data.value_format, {expires: 86400});
                        $('.okinus-widget .amount-remain .value').html(response.data.value_format);
                    });

                    $.ajax({
                        url: '/okinus/cart/paymentcalculator',
                        method: 'post'
                    }).done(function(response){
                        $.cookie('okinus_subtraction_amount', response.data.value, {expires: 86400});
                        $.cookie('okinus_subtraction_amount_format', response.data.value_format, {expires: 86400});
                        $('.okinus-widget .estimated-payment .value').html(response.data.value_format);

                    });
                    $.cookie('okinus_popup_status', 'open', {expires: 86400});
                    $.cookie('okinus_biweekly_amount', parseFloat(0.00), {expires: 86400});
                    $("#okinus-apply-button").hide();
                    $("#okinus-apply-button-product").hide();
                }
            });
        }

        $(document).on('click', '#okinus-apply-button', function(){
            initiateApply();
        })

        $(document).on('click', '#okinus-apply-button-product', function(){
            initiateApply();
        })
    })

</script>
